import SwiftUI

struct OnboardingView: View {
    @EnvironmentObject private var appState: AppState
    @State private var endpoint = ""
    @State private var token = ""
    @State private var displayName = "MacBook"
    @State private var biometrics = true
    @State private var isConnecting = false
    @State private var localError: String?

    var body: some View {
        ScrollView {
            VStack(spacing: 28) {
                VStack(spacing: 16) {
                    AppMark(size: 76)
                    VStack(spacing: 6) {
                        Text("HerdDeck")
                            .font(.system(size: 38, weight: .bold, design: .rounded))
                        Text("Your Herdr control room, built for touch.")
                            .font(.subheadline)
                            .foregroundStyle(.secondary)
                    }
                }
                .padding(.top, 34)

                GlassCard {
                    VStack(alignment: .leading, spacing: 20) {
                        VStack(alignment: .leading, spacing: 5) {
                            SectionEyebrow(text: "Connect")
                            Text("Pair with your Mac")
                                .font(.title3.weight(.semibold))
                            Text("Use the HTTPS address created by Tailscale Serve and the token generated by the Gateway.")
                                .font(.subheadline)
                                .foregroundStyle(.secondary)
                        }

                        LabeledContent {
                            TextField("https://mac.tailnet.ts.net", text: $endpoint)
                                .textInputAutocapitalization(.never)
                                .autocorrectionDisabled()
                                .keyboardType(.URL)
                                .multilineTextAlignment(.trailing)
                        } label: {
                            Label("Gateway", systemImage: "network")
                        }

                        Divider().opacity(0.4)

                        LabeledContent {
                            SecureField("Bearer token", text: $token)
                                .textInputAutocapitalization(.never)
                                .autocorrectionDisabled()
                                .multilineTextAlignment(.trailing)
                                .privacySensitive()
                        } label: {
                            Label("Token", systemImage: "key.fill")
                        }

                        Divider().opacity(0.4)

                        LabeledContent {
                            TextField("MacBook", text: $displayName)
                                .multilineTextAlignment(.trailing)
                        } label: {
                            Label("Name", systemImage: "laptopcomputer")
                        }

                        Toggle(isOn: $biometrics) {
                            Label("Require device authentication", systemImage: "faceid")
                        }

                        if let localError {
                            Label(localError, systemImage: "exclamationmark.triangle.fill")
                                .font(.caption)
                                .foregroundStyle(.herdAmber)
                        }

                        Button {
                            Task { await connect() }
                        } label: {
                            HStack {
                                if isConnecting { ProgressView().tint(.white) }
                                Text(isConnecting ? "Checking Gateway…" : "Pair securely")
                                Spacer()
                                Image(systemName: "arrow.right")
                            }
                            .frame(maxWidth: .infinity)
                        }
                        .buttonStyle(HerdDeckPrimaryButtonStyle())
                        .disabled(isConnecting || endpoint.isEmpty || token.isEmpty)
                    }
                }

                HStack(alignment: .top, spacing: 10) {
                    Image(systemName: "lock.shield.fill")
                        .foregroundStyle(.herdMint)
                    Text("HerdDeck never stores the token in UserDefaults. It is kept in this device’s Keychain and sent only to the configured HTTPS endpoint.")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
                .padding(.horizontal, 10)
            }
            .padding(.horizontal, 20)
            .padding(.bottom, 40)
            .frame(maxWidth: 620)
            .frame(maxWidth: .infinity)
        }
        .scrollDismissesKeyboard(.interactively)
        .onAppear { applyPairingPayload() }
        .onChange(of: appState.pairingPayload) { _, _ in applyPairingPayload() }
    }

    private func applyPairingPayload() {
        guard let payload = appState.pairingPayload else { return }
        endpoint = payload.endpoint
        token = payload.token
        displayName = payload.displayName
        appState.clearPairingPayload()
    }

    private func connect() async {
        isConnecting = true
        localError = nil
        defer { isConnecting = false }
        do {
            try await appState.configure(
                endpoint: endpoint,
                token: token,
                displayName: displayName,
                requiresBiometrics: biometrics
            )
        } catch {
            localError = error.localizedDescription
        }
    }
}
